version: "3"
   
services:
  db:
    image: postgres
    container_name: bmat_bo_db
    user: 1000:1000
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    container_name: bmat_bo_api
    build: .
    # command: cd app && python manage.py runserver 0.0.0.0:8000
    command: >
            bash -c "cd app && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  api-docs:
    image: swaggerapi/swagger-ui
    container_name: bmat_bo_api_docs
    ports:
      - "8001:8080"
    volumes:
      - ./openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
