# Generated by Django 3.2.10 on 2021-12-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='file',
            name='work_count',
            field=models.IntegerField(default=1),
        ),
    ]
