# Generated by Django 3.2.10 on 2021-12-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='contributers',
            new_name='contributors',
        ),
    ]
